interface PropertyAdapterType {
    reference: string;
    title: string;
    description: string;
    price: number;
    address: string;
    city: number;
    departament: number;
    building: number;
    contactName: string;
    contactPhone: string;
    contactEmail: string;
    contactCellphone: string;
    antiquityYears: number;
    lastAdminprice: number;
    neighborhood: string;
    propertyType: string;
    offer: number;
    area: number;
    stratum: number;
    bedrooms: number;
    numElevators: number;
    numFloor: number;
    bathrooms: number;
    garage: number;
    parking: number;
    remodelation: number;
    latitude: number;
    longitude: number;
    saleOff: number;
    files: string[];
}

export const createPropertyAdapter = (property: PropertyAdapterType) => ({
    reference: property.reference,
    title: property.title,
    description: property.description,
    price: property.price,
    address: property.address,
    city: property.city,
    departament: property.departament,
    building: property.building,
    contactName: property.contactName,
    contactPhone: property.contactPhone,
    contactEmail: property.contactEmail,
    contactCellphone: property.contactCellphone,
    antiquityYears: property.antiquityYears,
    lastAdminprice: property.lastAdminprice,
    neighborhood: property.neighborhood,
    propertyType: property.propertyType,
    offer: property.offer,
    area: property.area,
    stratum: property.stratum,
    bedrooms: property.bedrooms,
    numElevators: property.numElevators,
    numFloor: property.numFloor,
    bathrooms: property.bathrooms,
    garage: property.garage,
    parking: property.parking,
    remodelation: property.remodelation,
    latitude: property.latitude,
    longitude: property.longitude,
    saleOff: property.saleOff,
    files: property.files,
});
